univercity_schedule_student:
    resource: "@UnivercityScheduleBundle/Controller/StudentController.php"
    type:     annotation

univercity_schedule_groups:
    resource: "@UnivercityScheduleBundle/Controller/GroupsController.php"
    type:     annotation

univercity_schedule:
    resource: "@UnivercityScheduleBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
